package apolo.supervisor.com.utilidades

import apolo.supervisor.com.informes.TablasInformes
import apolo.supervisor.com.reportes.TablasReportes
import apolo.supervisor.com.visitas.TablasVisitas
import java.util.*

class TablasSincronizacion {

    private var tablasReportes : TablasReportes = TablasReportes()
    var tablasVisitas  : TablasVisitas  = TablasVisitas()
    private var tablasInformes : TablasInformes = TablasInformes()

    fun listaSQLCreateTables(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0, SentenciasSQL.createTableSvmControlVentaDiariaCab())
        lista.add(1, SentenciasSQL.createTableSvmControlVentaDiariaDet())
        lista.add(2, SentenciasSQL.createTableSvmMetasPuntoPorCliente())
        lista.add(3, SentenciasSQL.createTableSvmMetasPuntoPorLinea())
        lista.add(4, SentenciasSQL.createTableSvmEvolucionDiariaVenta())
        lista.add(5, SentenciasSQL.createTableSvmPrecioFijoConsulta())
        lista.add(6, SentenciasSQL.createTableSvmCostoVentaArticulo())
        lista.add(7, SentenciasSQL.createTableSvmDeudaPorClientes())
        lista.add(8, SentenciasSQL.createTableSvmRebotesPorCliente())
        lista.add(9, SentenciasSQL.createTableSvmSurtidoEficiente())
        lista.add(10, SentenciasSQL.createTableSvmMetasPuntoPorLineaEmpresa())
        lista.add(11, SentenciasSQL.createTableSvmPositivacionCliente())
        lista.add(12, SentenciasSQL.createTableSvmPedidosEnReparto())
        lista.add(13, SentenciasSQL.createTableSvmPremiosSupervisores())
        lista.add(14, SentenciasSQL.createTableSvmControlGeneralSup())
        lista.add(15, SentenciasSQL.createTableSvmClienteSupervisor())
        lista.add(16, SentenciasSQL.createTableSvmMotivoAnalisisCliente())
        lista.add(17, SentenciasSQL.createTableSvmMotivoAnalisisVendedor())
        lista.add(18, SentenciasSQL.createTableSvmClienteDiaVisitaRuteo())
        lista.add(19, SentenciasSQL.createTableSvmClientePromVendedor())
        lista.add(20, SentenciasSQL.createTableSvmCategoria())
        lista.add(21, SentenciasSQL.createTableSvmRetornoComentario())
        lista.add(22, SentenciasSQL.createTableSvmPeriodoFoto())
        lista.add(23, SentenciasSQL.createTableSvmClienteSupervisores())
        lista.add(24, SentenciasSQL.createTableSvmClienteListPrec())
        lista.add(25, SentenciasSQL.createTableSvmArticulosPrecios())
        lista.add(26, SentenciasSQL.createTableSvmStArticulos())
        lista.add(27, SentenciasSQL.createTableSvmCondicionVenta())
        lista.add(28, SentenciasSQL.createTableSvmVendedorPedido())
        lista.add(29, SentenciasSQL.createTableSvmClienteVendedor())
        lista.add(30, SentenciasSQL.createTableSvmUltimaVentaCliente())
        lista.add(31, SentenciasSQL.createTableSvmPromArticulosTarCred())
        lista.add(32, SentenciasSQL.createTableSvmCondVentaVendedor())
        lista.add(33, SentenciasSQL.createTableSvmMotivoNoVenta())
        lista.add(34, SentenciasSQL.createTableSvmPromocionesPerfilMerc())
        lista.add(35, SentenciasSQL.createTableSvmMovimientoGestor())
        lista.add(36, SentenciasSQL.createTableSvmPromocionesArtCab())
        lista.add(37, SentenciasSQL.createTableSvmPromocionesArtDet())
        lista.add(38, SentenciasSQL.createTableSvmSegVisitasSemanal())
        lista.add(39, SentenciasSQL.createTableSvmLiqComisionSupervisor())
        lista.add(40, SentenciasSQL.createTableSvmLiqPremiosVend())
        lista.add(41, SentenciasSQL.createTableSvmProduccionSemanalVend())
        lista.add(42, SentenciasSQL.createTableSvmLiqPremiosSup())
        lista.add(43, SentenciasSQL.createTableSvmCoberturaMarcaSup())
        lista.add(44, SentenciasSQL.createTableSvmCoberturaVisVendedores())
        lista.add(45, SentenciasSQL.createTableSvmLiquidacionFuerzaVenta())
        lista.add(46, SentenciasSQL.createTableSvmMotivosSdDev())
        lista.add(47, SentenciasSQL.createTableSvmLiqCuotaXUnidadNegVend())
        lista.add(48, SentenciasSQL.createTableSvmCoberturaMensualVend())
        lista.add(49, SentenciasSQL.createTableSvmLiqCanastaCteSup())
        lista.add(50, SentenciasSQL.createTableSvmLiqCanastaMarcaSup())
        lista.add(51, SentenciasSQL.createTableSvmProduccionSemanal())
        lista.add(52, SentenciasSQL.createTableSvmPromAlcCuotaMensualSup())
        lista.add(53, SentenciasSQL.createTableSvmLiqCuotaXUnidadNeg())
        lista.add(54, SentenciasSQL.createTableSvmCoberturaMensualSup())
        lista.add(55, SentenciasSQL.createTableSvmCobSemanalVend())

        return lista
    }

    fun listaCamposSincronizacion(): Vector<Vector<String>> {
        val lista : Vector<Vector<String>> = Vector()
        lista.add(0,tablasInformes.camposTablaSvmControlVentaDiariaCab())
        lista.add(1,tablasInformes.camposTablaSvmControlVentaDiariaDet())
        lista.add(2,tablasInformes.camposTablaSvmMetasPuntoPorCliente())
        lista.add(3,camposTablaSvmMetasPuntoPorLinea())
        lista.add(4,tablasInformes.camposTablaSvmEvolDiariaVenta())
        lista.add(5,tablasInformes.camposTablaSvmPrecioFijoConsulta())
        lista.add(6,camposTablaSvmCostoVentaArticulo())
        lista.add(7,tablasInformes.camposTablaSvmDeudaCliente())
        lista.add(8,tablasInformes.camposTablaSvmRebotesPorCliente())
        lista.add(9,camposTablaSvmSurtidoEficiente())
        lista.add(10,camposTablaSvmMetasPuntoPorLineaEmpresa())
        lista.add(11,camposTablaSvmPositivacionCliente())
        lista.add(12,tablasInformes.camposTablaSvmPedidosEnReparto())
        lista.add(13,camposTablaSvmPremiosSupervisores())
        lista.add(14,camposTablaSvmControlGeneralSup())
        lista.add(15,tablasVisitas.camposTablaSvmClienteSupervisor())
        lista.add(16,tablasVisitas.camposTablaSvmMotivoAnalisisCliente())
        lista.add(17,camposTablaSvmMotivoAnalisisVendedor())
        lista.add(18,tablasInformes.camposTablaSvmClienteDiaVisitaRuteo())
        lista.add(19,camposTablaSvmClientePromVendedor())
        lista.add(20,camposTablaSvmCategoria())
        lista.add(21,camposTablaSvmRetornoComentario())
        lista.add(22,camposTablaSvmPeriodoFoto())
        lista.add(23,tablasVisitas.camposTablaSvmClienteSupervisores())
        lista.add(24,camposTablaSvmClienteListPrec())
        lista.add(25,camposTablaSvmArticulosPrecios())
        lista.add(26,camposTablaSvmStArticulos())
        lista.add(27,camposTablaSvmCondicionVenta())
        lista.add(28,camposTablaSvmVendedorPedido())
        lista.add(29,camposTablaSvmClienteVendedor())
        lista.add(30,camposTablaSvmUltimaVentaCliente())
        lista.add(31,camposTablaSvmPromArticulosTarCred())
        lista.add(32,camposTablaSvmCondVentaVendedor())
        lista.add(33,camposTablaSvmMotivoNoVenta())
        lista.add(34,camposTablaSvmPromocionesPerfilMerc())
        lista.add(35,tablasInformes.camposTablaSvmMovimientoGestor())
        lista.add(36,camposTablaSvmPromocionesArtCab())
        lista.add(37,camposTablaSvmPromocionesArtDet())
        lista.add(38,tablasInformes.camposTablaSvmSegVisitasSemanal())
        lista.add(39,tablasReportes.camposTablaSvmLiqComisionSupervisor())
        lista.add(40,tablasInformes.camposTablaSvmLiqPremiosVend())
        lista.add(41,camposTablaSvmProduccionSemanalVend())
        lista.add(42,tablasReportes.camposTablaSvmLiqPremiosSup())
        lista.add(43,camposTablaSvmCoberturaMarcaSup())
        lista.add(44,camposTablaSvmCoberturaVisVendedores())
        lista.add(45,tablasReportes.camposTablaSvmLiquidacionFuerzaVenta())
        lista.add(46,camposTablaSvmMotivosSdDev())
        lista.add(47,tablasInformes.camposTablaSvmLiqCuotaXUndNegVend())
        lista.add(48,tablasInformes.svmCoberturaMensualVend())
        lista.add(49,tablasReportes.camposTablaSvmLiqCanastaCteSup())
        lista.add(50,tablasReportes.camposTablaSvmLiqCanastaMarcaSup())
        lista.add(51,tablasReportes.camposTablaSvmProduccionSemanal())
        lista.add(52,tablasInformes.camposTablaSvmPromAlcCuotaMensualSup())
        lista.add(53,tablasReportes.camposTablaSvmLiqCuotaXUndNeg())
        lista.add(54,tablasReportes.camposTablaSvmCoberturaMensualSup())
        lista.add(55,tablasInformes.camposTablaSvmCobSemanalVend())

        return lista
    }

    private fun camposTablaSvmMetasPuntoPorLinea(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"COD_LINEA")
        lista.add(4,"DESC_LINEA")
        lista.add(5,"ABREV")
        lista.add(6,"DESC_GTE_MARKETIN")
        lista.add(7,"DESC_MODULO")
        lista.add(8,"COD_SUPERVISOR")
        lista.add(9,"DESC_SUPERVISOR")
        lista.add(10,"MAYOR_VENTA")
        lista.add(11,"VENTA_3")
        lista.add(12,"VENTA_4")
        lista.add(13,"METAS")
        lista.add(14,"NRO_ORD_MAG")
        lista.add(15,"ORD_GTE_MARK")
        lista.add(16,"ORD_CATEGORIA")
        lista.add(17,"MES_1")
        lista.add(18,"MES_2")
        lista.add(19,"")
        return lista
    }
    private fun camposTablaSvmCostoVentaArticulo(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_SUCURSAL")
        lista.add(2,"DESC_SUCURSAL")
        lista.add(3,"COD_ARTICULO")
        lista.add(4,"REFERENCIA")
        lista.add(5,"COSTO_VENTA")
        lista.add(6,"")
        return lista
    }
    private fun camposTablaSvmSurtidoEficiente(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"COD_CLIENTE")
        lista.add(4,"COD_SUBCLIENTE")
        lista.add(5,"TIP_CLIENTE")
        lista.add(6,"COD_ARTICULO")
        lista.add(7,"TIP_SURTIDO")
        lista.add(8,"")
        return lista
    }
    private fun camposTablaSvmMetasPuntoPorLineaEmpresa(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"METAS")
        lista.add(2,"VENTA")
        lista.add(3,"CANT_PUNTO")
        lista.add(4,"PUNT_ACUM")
        lista.add(5,"")
        return lista
    }
    private fun camposTablaSvmPositivacionCliente(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"TIP_CAUSAL")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"COD_SUBCLIENTE")
        lista.add(6,"DESC_CLIENTE")
        lista.add(7,"DESC_SUBCLIENTE")
        lista.add(8,"DIRECCION")
        lista.add(9,"DESC_CIUDAD")
        lista.add(10,"RUC")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DESC_ZONA")
        lista.add(13,"TELEFONO")
        lista.add(14,"IND_POS")
        lista.add(15,"MONTO_VENTA")
        lista.add(16,"COD_SUPERVISOR")
        lista.add(17,"")
        return lista
    }
    private fun camposTablaSvmPremiosSupervisores(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MARCA")
        lista.add(2,"DESC_MARCA")
        lista.add(3,"FEC_COMPROBANTE")
        lista.add(4,"VENTA")
        lista.add(5,"META")
        lista.add(6,"CANT_PUNTO")
        lista.add(7,"PORC_CUMP")
        lista.add(8,"PUNT_ACUM")
        lista.add(9,"")
        return lista
    }
    private fun camposTablaSvmControlGeneralSup(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_SUPERVISOR")
        lista.add(1,"DESC_SUPERVISOR")
        lista.add(2,"NRO_ORDEN")
        lista.add(3,"METAS")
        lista.add(4,"VENTAS")
        lista.add(5,"PORC_VOL_VENTAS")
        lista.add(6,"PUNT_ACUM_LINEAS")
        lista.add(7,"PUNT_CLI_ACUM")
        lista.add(8,"CANT_CLI_POS")
        lista.add(9,"MONTO_REBOTE")
        lista.add(10,"MONTO_DEV")
        lista.add(11,"CANT_COB")
        lista.add(12,"CANT_RUTEO")
        lista.add(13,"VENTAS_ESTR")
        lista.add(14,"METAS_ESTR")
        lista.add(15,"CATASTRO")
        lista.add(16,"PORC_MONTO_REBOTE")
        lista.add(17,"PORC_MONTO_DEV")
        lista.add(18,"")
        return lista
    }
    private fun camposTablaSvmMotivoAnalisisVendedor(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_MOTIVO")
        lista.add(1,"DESCRIPCION")
        lista.add(2,"ESTADO")
        lista.add(3,"PUNTUACION")
        lista.add(4,"COD_VENDEDOR")
        lista.add(5,"COD_GRUPO")
        lista.add(6,"NRO_ORDEN")
        lista.add(7,"")
        return lista
    }
    private fun camposTablaSvmClientePromVendedor(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"DESC_CLIENTE")
        lista.add(5,"COD_VENDEDOR")
        lista.add(6,"TELEFONO")
        lista.add(7,"RUC")
        lista.add(8,"TIP_CAUSAL")
        lista.add(9,"desc_ciudad")
        lista.add(10,"DESC_ZONA")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DIRECCION")
        lista.add(13,"TELEFONO")
        lista.add(14,"COD_SUCURSAL")
        lista.add(15,"DESC_TIPO")
        lista.add(16,"COD_CONDICION")
        lista.add(17,"DESC_CONDICION")
        lista.add(18,"LIMITE_CREDITO")
        lista.add(19,"TOT_DEUDA")
        lista.add(20,"SALDO")
        lista.add(21,"FEC_VISITA")
        lista.add(22,"IND_VISITA")
        lista.add(23,"COD_ZONA")
        lista.add(24,"TIPO_CONDICION")
        lista.add(25,"IND_DIRECTA")
        lista.add(26,"IND_ATRAZO")
        lista.add(27,"FRECUENCIA")
        lista.add(28,"COMENTARIO")
        lista.add(29,"IND_ESP")
        lista.add(30,"CATEGORIA")
        lista.add(31,"TELEFONO2")
        lista.add(32,"LATITUD")
        lista.add(33,"LONGITUD")
        lista.add(34,"CERCA_DE")
        lista.add(35,"IND_CADUCADO")
        lista.add(36,"TIP_CLIENTE")
        lista.add(37,"IND_VITRINA")
        lista.add(38,"FOTO_FACHADA")
        lista.add(39,"TIEMPO_MIN")
        lista.add(40,"TIEMPO_MAX")
        lista.add(41,"DIAS_INICIAL")
        lista.add(42,"")

        return lista
    }
    private fun camposTablaSvmCategoria(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CATEGORIA")
        lista.add(2,"DESC_CATEGORIA")
        lista.add(3,"COD_SEGMENTO")
        lista.add(4,"DESC_SEGMENTO")
        lista.add(5,"ORDEN")
        lista.add(6,"TIPO")
        lista.add(7,"COD_TIP_CLIENTE")
        lista.add(8,"")
        return lista
    }
    private fun camposTablaSvmRetornoComentario(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"FEC_ENTRADA")
        lista.add(2,"FEC_SALIDA")
        lista.add(3,"COD_PROMOTOR")
        lista.add(4,"COD_CLIENTE")
        lista.add(5,"COD_SUBCLIENTE")
        lista.add(6,"COD_CATEGORIA")
        lista.add(7,"COD_SEGMENTO")
        lista.add(8,"TIPO")
        lista.add(9,"PUNTUACION")
        lista.add(10,"COMENTARIO_SUPERVISOR")
        lista.add(11,"")
        return lista
    }
    private fun camposTablaSvmPeriodoFoto(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_TIP_CLIENTE")
        lista.add(2,"FEC_INICIO")
        lista.add(3,"FEC_FIN")
        lista.add(4,"")
        return lista
    }
    private fun camposTablaSvmClienteListPrec(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"COD_VENDEDOR")
        lista.add(4,"COD_LISTA_PRECIO")
        lista.add(5,"DESC_LISTA")
        lista.add(6,"IND_DEFECTO")
        lista.add(7,"COD_MONEDA")
        lista.add(8,"DECIMALES")
        lista.add(9,"")
        return lista
    }
    private fun camposTablaSvmArticulosPrecios(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"MODULO")
        lista.add(3,"COD_LISTA_PRECIO")
        lista.add(4,"COD_ARTICULO")
        lista.add(5,"DESC_ARTICULO")
        lista.add(6,"PREC_CAJA")
        lista.add(7,"PREC_UNID")
        lista.add(8,"COD_UNIDAD_MEDIDA")
        lista.add(9,"PORC_IVA")
        lista.add(10,"REFERENCIA")
        lista.add(11,"MULT")
        lista.add(12,"DIV")
        lista.add(13,"IND_LIM_VENTA")
        lista.add(14,"COD_LINEA")
        lista.add(15,"COD_FAMILIA")
        lista.add(16,"COD_BARRA")
        lista.add(17,"CANT_MINIMA")
        lista.add(18,"PORC_DESCUENTO")
        lista.add(19,"")
        return lista
    }
    private fun camposTablaSvmStArticulos(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"cod_empresa")
        lista.add(1,"cod_articulo")
        lista.add(2,"desc_articulo")
        lista.add(3,"cod_unidad_rel")
        lista.add(4,"referencia")
        lista.add(5,"mult")
        lista.add(6,"div")
        lista.add(7,"cod_iva")
        lista.add(8,"porc_iva")
        lista.add(9,"cod_linea")
        lista.add(10,"cod_familia")
        lista.add(11,"CANT_MINIMA")
        lista.add(12,"CONT_EXIST")
        lista.add(13,"ind_basico")
        lista.add(14,"")
        return lista
    }
    private fun camposTablaSvmCondicionVenta(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"cod_empresa")
        lista.add(1,"cod_condicion_venta")
        lista.add(2,"descripcion")
        lista.add(3,"tipo_condicion")
        lista.add(4,"abreviatura")
        lista.add(5,"dias_inicial")
        lista.add(6,"porc_desc")
        lista.add(7,"porc_desc")
        lista.add(8,"")
        return lista
    }
    private fun camposTablaSvmVendedorPedido(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"IND_PALM")
        lista.add(3,"TIPO")
        lista.add(4,"SERIE")
        lista.add(5,"NUMERO")
        lista.add(6,"FECHA")
        lista.add(7,"COD_CLI_VEND")
        lista.add(8,"COD_PERSONA")
        lista.add(9,"RANGO")
        lista.add(10,"MIN_FOTOS")
        lista.add(11,"MAX_FOTOS")
        lista.add(12,"PER_VENDER")
        lista.add(13,"PER_PRESENCIAL")
        lista.add(14,"HORA")
        lista.add(15,"VERSION_SISTEMA")
        lista.add(16,"PER_ASISTENCIA")
        lista.add(17,"FRECUENCIA_RASTREO")
        lista.add(18,"HORA_INICIO")
        lista.add(19,"HORA_FIN")
        lista.add(20,"TIEMPO_ASISTENCIA")
        lista.add(21,"IND_FOTO")
        lista.add(22,"MIN_VENTA")
        lista.add(23,"VERSION")
        lista.add(24,"")
//        lista.add(25,"")
//        lista.add(26,"")
//        lista.add(27,"")
//        lista.add(28,"ULTIMA_VEZ")
//        lista.add(29,"ultima_sincro")
        return lista
    }
    private fun camposTablaSvmClienteVendedor(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_SUBCLIENTE")
        lista.add(3,"DESC_SUBCLIENTE")
        lista.add(4,"DESC_CLIENTE")
        lista.add(5,"COD_VENDEDOR")
        lista.add(6,"TELEFONO")
        lista.add(7,"RUC")
        lista.add(8,"TIP_CAUSAL")
        lista.add(9,"desc_ciudad")
        lista.add(10,"DESC_ZONA")
        lista.add(11,"DESC_REGION")
        lista.add(12,"DIRECCION")
        lista.add(13,"TELEFONO")
        lista.add(14,"COD_SUCURSAL")
        lista.add(15,"DESC_TIPO")
        lista.add(16,"COD_CONDICION")
        lista.add(17,"DESC_CONDICION")
        lista.add(18,"LIMITE_CREDITO")
        lista.add(19,"TOT_DEUDA")
        lista.add(20,"SALDO")
        lista.add(21,"FEC_VISITA")
        lista.add(22,"IND_VISITA")
        lista.add(23,"COD_ZONA")
        lista.add(24,"TIPO_CONDICION")
        lista.add(25,"IND_DIRECTA")
        lista.add(26,"IND_ATRAZO")
        lista.add(27,"FRECUENCIA")
        lista.add(28,"COMENTARIO")
        lista.add(29,"IND_ESP")
        lista.add(30,"CATEGORIA")
        lista.add(31,"TELEFONO2")
        lista.add(32,"LATITUD")
        lista.add(33,"LONGITUD")
        lista.add(34,"CERCA_DE")
        lista.add(35,"IND_CADUCADO")
        lista.add(36,"TIP_CLIENTE")
        lista.add(37,"IND_VITRINA")
        lista.add(38,"FOTO_FACHADA")
        lista.add(39,"TIEMPO_MIN")
        lista.add(40,"TIEMPO_MAX")
        lista.add(41,"SOL_TARG")
        lista.add(42,"DIAS_INICIAL")
        lista.add(43,"")
        return lista
    }
    private fun camposTablaSvmUltimaVentaCliente(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_CLIENTE")
        lista.add(2,"COD_VENDEDOR")
        lista.add(3,"COD_SUBCLIENTE")
        lista.add(4,"FEC_COMPROBANTE")
        lista.add(5,"COD_ARTICULO")
        lista.add(6,"PRECIO_UNITARIO")
        lista.add(7,"CANTIDAD")
        lista.add(8,"DESC_UNIDAD")
        lista.add(9,"SIGLAS")
        lista.add(10,"DESC_ARTICULO")
        lista.add(11,"DECIMALES")
        lista.add(12,"")
        return lista
    }
    private fun camposTablaSvmPromArticulosTarCred(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"NRO_PROMOCION")
        lista.add(2,"COD_CONDICION_VENTA")
        lista.add(3,"COD_ARTICULO")
        lista.add(4,"DESC_ARTICULO")
        lista.add(5,"PORC_DESCUENTO")
        lista.add(6,"DESCRIPCION")
        lista.add(7,"COMENTARIO")
        lista.add(8,"")
        return lista
    }
    private fun camposTablaSvmCondVentaVendedor(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_LISTA_PRECIO")
        lista.add(3,"COD_CLIENTE")
        lista.add(4,"COD_SUBCLIENTE")
        lista.add(5,"COD_CONDICION_VENTA")
        lista.add(6,"")
        return lista
    }
    private fun camposTablaSvmMotivoNoVenta(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"CIERRA")
        lista.add(3,"DESC_MOTIVO")
        lista.add(4,"")
        return lista
    }
    private fun camposTablaSvmPromocionesPerfilMerc(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"TIP_CLIENTE")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"DESCRIPCION")
        lista.add(4,"COMENTARIO")
        lista.add(5,"FEC_INI_PROMO")
        lista.add(6,"FEC_FIN_PROMO")
        lista.add(7,"COD_ARTICULO")
        lista.add(8,"")
        return lista
    }
    private fun camposTablaSvmPromocionesArtCab(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"COD_UNID_NEGOCIO")
        lista.add(4,"TIP_CLIENTE")
        lista.add(5,"DESCRIPCION")
        lista.add(6,"COMENTARIO")
        lista.add(7,"COD_CONDICION_VENTA")
        lista.add(8,"FEC_VIGENCIA")
        lista.add(9,"COD_ARTICULO")
        lista.add(10,"DESC_ARTICULO")
        lista.add(11,"COD_UNIDAD_MEDIDA")
        lista.add(12,"REFERENCIA")
        lista.add(13,"IND_TIPO")
        lista.add(14,"MULT")
        lista.add(15,"COD_LISTA_PRECIO")
        lista.add(16,"IND_COMBO")
        lista.add(17,"IND_PROM")
        lista.add(18,"IND_ART")
        lista.add(19,"CANT_VENTA")
        lista.add(20,"")
        return lista
    }
    private fun camposTablaSvmPromocionesArtDet(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"NRO_PROMOCION")
        lista.add(3,"COD_UNID_NEGOCIO")
        lista.add(4,"CANT_DESDE")
        lista.add(5,"CANT_HASTA")
        lista.add(6,"COD_ARTICULO")
        lista.add(7,"COD_UNIDAD_MEDIDA")
        lista.add(8,"DESC_UND_MEDIDA")
        lista.add(9,"IND_TIPO")
        lista.add(10,"DESCUENTO")
        lista.add(11,"PRECIO_GS")
        lista.add(12,"IND_MULTIPLE")
        lista.add(13,"PRECIO_RS")
        lista.add(14,"")
        return lista
    }
    private fun camposTablaSvmProduccionSemanalVend(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"COD_PERSONA")
        lista.add(3,"DESC_VENDEDOR")
        lista.add(4,"CANTIDAD")
        lista.add(5,"SEMANA")
        lista.add(6,"FECHA")
        lista.add(7,"MONTO_VIATICO")
        lista.add(8,"MONTO_TOTAL")
        lista.add(9,"PERIODO")
        lista.add(10,"")
        return lista
    }
    private fun camposTablaSvmCoberturaMarcaSup(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"PORC_DESDE")
        lista.add(2,"PORC_HASTA")
        lista.add(3,"PORC_COM")
        lista.add(4,"LINHA")
        lista.add(5,"")
        return lista
    }
    private fun camposTablaSvmCoberturaVisVendedores(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_GRUPO")
        lista.add(1,"COD_VENDEDOR")
        lista.add(2,"DESC_VENDEDOR")
        lista.add(3,"PORC_DESDE")
        lista.add(4,"PORC_HASTA")
        lista.add(5,"PORC_COM")
        lista.add(6,"")
        return lista
    }
    private fun camposTablaSvmMotivosSdDev(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"DESC_MOTIVO")
        lista.add(3,"")
        return lista
    }

//    fun camposTablaS(): Vector<String> {
//        var lista : Vector<String> = Vector<String>()
//        lista.add(0,"")
//        lista.add(1,"")
//        lista.add(2,"")
//        lista.add(3,"")
//        lista.add(4,"")
//        lista.add(5,"")
//        lista.add(6,"")
//        lista.add(7,"")
//        lista.add(8,"")
//        lista.add(9,"")
//        lista.add(10,"")
//        lista.add(11,"")
//        lista.add(12,"")
//        lista.add(13,"")
//        lista.add(14,"")
//        lista.add(15,"")
//        lista.add(16,"")
//        lista.add(17,"")
//        lista.add(18,"")
//        lista.add(19,"")
//        lista.add(20,"")
//        lista.add(21,"")
//        lista.add(22,"")
//        lista.add(23,"")
//        lista.add(24,"")
//        lista.add(25,"")
//        lista.add(26,"")
//        lista.add(27,"")
//        lista.add(28,"")
//        lista.add(29,"")
//        return lista
//    }


}